#!/usr/bin/env python3
"""Assemble the Shopify theme files from the game's own sources, so index.html,
game.js and game.css stay the single source of truth.

  shopify/theme/sections/flavor-mash-game.liquid   markup from index.html + settings
  shopify/theme/assets/mm-*                        game.js/css, manifest, art, sound
  shopify/theme/templates/page.flavor-mash.json    a page template carrying the section

Copy shopify/theme/* into a pulled theme and `shopify theme push`."""
import json, pathlib, re, shutil
root = pathlib.Path(__file__).parent
out  = root / "shopify" / "theme"
shutil.rmtree(out, ignore_errors=True)
for d in ("sections", "assets", "templates"): (out / d).mkdir(parents=True)

# assets: one flat folder, prefixed so nothing collides with the theme's own
shutil.copy(root / "game.js",  out / "assets/mm-game.js")
shutil.copy(root / "game.css", out / "assets/mm-game.css")
for f in (root / "build-assets").iterdir():
    if f.suffix in (".webp", ".json"): shutil.copy(f, out / "assets" / ("mm-" + f.name))
for f in (root / "audio").glob("*.mp3"): shutil.copy(f, out / "assets" / ("mm-" + f.name))

markup = re.search(r'(<div id="mm-game">.*?\n</div>\n)\n<script', (root / "index.html").read_text(), re.S).group(1)
markup = re.sub(r"\n<!--.*?-->", "", markup, flags=re.S)          # the file's own notes

section = r'''{%- comment -%}
  Franken Chewbie's Flavor Mash. Generated by build_theme.py from the game
  repo — edit there, not here. The game runs inline in #mm-game; entries POST
  to the API URL below, which forwards to Mailchimp.
{%- endcomment -%}
{{ 'mm-game.css' | asset_url | stylesheet_tag }}
<style>
  /* the Easter page's framing */
  .mm-wrap{
    align-items:center; display:flex; flex-direction:column;
    gap:5rem; padding:8rem 0 15rem;
    background:{{ section.settings.bg_color }};
    {%- if section.settings.bg_image != blank %}
    background-image:url({{ section.settings.bg_image | image_url: width: 2400 }});
    background-size:cover; background-position:center;
    {%- endif %}
  }
  .mm-frame{
    position:relative;
    width:{{ section.settings.width_pct }}%;
    max-width:{{ section.settings.max_width }}px;
    aspect-ratio:4/3; max-height:{{ section.settings.max_height }}px;   /* desktop art is 4:3 */
  }
  @media (max-width:767px){
    .mm-frame{ aspect-ratio:9/16; max-height:none; }                    /* mobile art is 9:16 */
  }
  .mm-frame #mm-game{ border:7px solid #FFF; border-radius:20px; }
</style>

<div class="mm-wrap">
  <div class="mm-frame">
MARKUP
  </div>
</div>

{%- assign manifest_url = 'mm-manifest.json' | asset_url -%}
{%- assign asset_base = manifest_url | split: '?' | first | replace: 'mm-manifest.json', '' -%}
<script>
  window.FLAVOR_MASH_CONFIG = {
    art: {{ asset_base | json }},
    audio: {{ asset_base | json }},
    prefix: "mm-",
    manifest: {{ manifest_url | json }},
    api: {{ section.settings.api_url | json }},
    recaptchaKey: {{ section.settings.recaptcha_key | json }},
    audioMode: {{ section.settings.audio_mode | json }}
  };
</script>
{%- if section.settings.recaptcha_key != blank %}
<script src="https://www.google.com/recaptcha/api.js?render={{ section.settings.recaptcha_key }}" async></script>
{%- endif %}
{{ 'mm-game.js' | asset_url | script_tag }}

{% schema %}
{
  "name": "Flavor Mash Game",
  "settings": [
    { "type": "text", "id": "api_url", "label": "Entry API URL",
      "default": "https://hi-chew-mystery-mix.vercel.app/api/subscribe",
      "info": "Receives each entry and forwards it to Mailchimp. Leave blank to preview without sending." },
    { "type": "text", "id": "recaptcha_key", "label": "reCAPTCHA site key",
      "info": "Same key as the Easter game's section. Blank = no bot check." },
    { "type": "select", "id": "audio_mode", "label": "Music",
      "options": [ { "value": "a", "label": "Throughout" },
                   { "value": "b", "label": "Title and thank-you screens only" } ],
      "default": "a" },
    { "type": "header", "content": "Frame" },
    { "type": "color", "id": "bg_color", "label": "Page colour", "default": "#740494" },
    { "type": "image_picker", "id": "bg_image", "label": "Page background",
      "info": "Full-bleed behind the game, as on the Easter page." },
    { "type": "range", "id": "width_pct", "label": "Width of the page",
      "min": 40, "max": 100, "step": 2, "unit": "%", "default": 90 },
    { "type": "range", "id": "max_width", "label": "Maximum width",
      "min": 600, "max": 1400, "step": 50, "unit": "px", "default": 1100 },
    { "type": "range", "id": "max_height", "label": "Maximum height",
      "min": 500, "max": 1200, "step": 10, "unit": "px", "default": 870,
      "info": "The frame keeps the art's shape (4:3, or 9:16 on phones) up to this height." }
  ],
  "presets": [ { "name": "Flavor Mash Game" } ]
}
{% endschema %}
'''.replace("MARKUP", "    " + markup.strip().replace("\n", "\n    "))
(out / "sections/flavor-mash-game.liquid").write_text(section)
(out / "templates/page.flavor-mash.json").write_text(json.dumps({
    "sections": { "game": { "type": "flavor-mash-game", "settings": {
        "api_url": "https://hi-chew-mystery-mix.vercel.app/api/subscribe",
        "recaptcha_key": "6Lf0rrQtAAAAAE2ZyVTm7Aag1r5WPJRPtVn4XALK",   # Multiply.s v3 key, Sep 10 2026
        "audio_mode": "a" } } },
    "order": ["game"]
}, indent=2) + "\n")
n = len(list((out / "assets").iterdir()))
print(f"theme built: {n} assets, section, template → {out.relative_to(root)}")
